title: Rafael Varago's Tech Blog
author: Rafael Varago
description: Thoughts on programming, mostly

url: https://rvarago.github.io

email: rafael.varago@gmail.com
github_username: rvarago
linkedin_username: rafaelvarago
medium_username: rvarago

header_pages:
  - index.html
  - about.md
  - tags.html

markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 15
paginate_path: /page:num/
