#+begin_export html
---
layout: post
title: Integrating a trigonometric expression for fun
permalink: /:title/
tags: [math]
mathjax: true
---
#+end_export

#+begin_quote
(WIP)
I stumbled upon an exercise to integrate a function involving trigonometric identities. So, I reckoned it'd be fun tackling it.
#+end_quote
--------------

It's been years since I solved an [[https://en.wikipedia.org/wiki/Integral][integration]] exercise.

I remember having fun trying to find patterns that'd eventually lead me to an analytical solution and rediscovering properties of different functions and useful identities in the way.

The process often involved [[https://en.wikipedia.org/wiki/List_of_trigonometric_identities][trigonometric identities]] and I always had troubles committing them all to memory, except perhaps for the top Pythagorean identity:

\[
\sin^2 x + \cos^2 x = 1
\]

And the angle sum, e.g. for \( \sin \):

\[
\sin (\alpha + \beta) = \sin \alpha \cos \beta + \sin \beta \cos \alpha
\]

Thankfully, they suffice to mechanically derive much of the rest.

* The challenge
Weeks ago I took a stab at this brief exercise I found somewhere:

\[
\int_0^{\frac{\pi}{2}} (\sin x + \cos x)^2 \, dx
\]

It looked like a good opportunity to play around and refresh my working memory on integrals and trigonometry in general without taking too much time.

* The solution
I started off by expanding \( (\sin x + \cos x)^2 \) into:

\[
\sin^2 x + 2\sin x\cos x + \cos^2 x
\]

I recognised the sum of the first and last terms as equal to \( 1 \) -- per the Pythegorean identity:

\[
1 + 2\sin x \cos x
\]

I remembered \( 2\sin x \cos x \) could be simplified with the double-angle identity for \( \sin \):

\[
\sin(2x) = 2\sin x\cos x
\]

#+BEGIN_EXPORT html
<details>
  <summary>Deriving the double-angle identity</summary>
  By algebraic manipulation and application of the angle sum identity for \( \sin \):
  \[
  \sin(2x) \\
  = \sin(x + x) \\
  = \sin x\cos x + \sin x\cos x = 2\sin x\cos x \\
  \blacksquare
  \]
</details>
#+END_EXPORT

Leaving us with this simpler integrand:

\[
1 + \sin(2x)
\]
