#+begin_export html
---
layout: post
title: Integrating a trigonometric expression for fun
permalink: /:title/
tags: [math]
mathjax: true
---
#+end_export

#+begin_quote
(WIP)
I stumbled upon an exercise to integrate a function involving trigonometric identities, it'd been
a while since I last did anything similar. So, I reckoned it'd be writing about it.
#+end_quote
--------------

It's been years, perhaps far more than I'd like to admit, since I resolve an [[https://en.wikipedia.org/wiki/Integral][integration]] problem.

I remember having fun trying to find patterns in integrands that'd eventually lead me to an analytical solution and learning properties of different functions in the way. It'd often involve [[https://en.wikipedia.org/wiki/List_of_trigonometric_identities][trigonometric identities]] and I always had troubles committing them all to memory, except perhaps for the beautiful most important Pythagorean identity:

\[
\sin^2 x + \cos^2 x = 1
\]

And the angle sum, e.g. for \( \sin \):

\[
\sin (\alpha + \beta) = \sin \alpha \cos \alpha + \sin \beta \cos \alpha
\]

Thankfully, they suffice to mechanically derive plenty of rest.

* The challenge
Weeks ago I took a stab at this brief exercise I found somewhere:

\[
\int_0^{\frac{\pi}{2}} (\sin x + \cos x)^2 \, dx
\]

Nice! Good chance to play around and refresh my working memory on integrals and trigonometry without taking too much time (hopefully).

* The solution
I started off by expanding \( (\sin x + \cos x)^2 \) into:

\[
\sin^2 x + 2\sin x\cos x + \cos^2 x
\]

I recognised the sum of the first and last terms as equal to \( 1 \) -- per the Pythegorean identity:

\[
1 + 2\sin x \cos x
\]

Ok. I remembered \( 2\sin x \cos x \) could be simplified with the double-angle identity for \( \sin \):
\[
\sin(2x) = 2\sin x\cos x
\]

#+BEGIN_EXPORT html
<details>
  <summary>Deriving the last identity</summary>
  By algebraic manipulation and application of the angle sum identity for \( \sin \):
  \[
  \sin(2x) \leftrightarrow \sin(x + x) \leftrightarrow \sin x\cos x + \sin x\cos x = 2\sin x\cos x \blacksquare
  \]
</details>
#+END_EXPORT

Leaving us with this simpler integrand:
\[
1 + \sin(2x)
\]
