#+begin_export html
---
layout: post
title: Testabilidade e Injeção de Dependências em Software Embarcado
permalink: /:title/
tags: [testes c++]
---
#+end_export

#+begin_quote
Uma breve introdução a técnicas de injeção de dependências em C++ para testes unitários de software embarcado.
#+end_quote
---------------

* Introdução
A testabilidade é um aspecto crucial no desenvolvimento de sistemas embarcados, especialmente devido ao impacto significativo que esses dispositivos têm em contextos críticos, como veículos, equipamentos médicos e sistemas industriais. Testes unitários, nesse cenário, assumem um papel estratégico ao permitir a validação isolada de cada unidade de código. Isso contribui para a detecção precoce de defeitos, reduzindo os riscos associados à integração de componentes e oferecendo feedback contínuo durante o desenvolvimento.

Entretanto, o ambiente embarcado apresenta desafios únicos, como restrições de hardware, recursos computacionais limitados e dificuldades para simular cenários críticos. Esses fatores reforçam ainda mais a necessidade de uma abordagem estruturada para testes.

Neste artigo, exploraremos estratégias práticas para isolar e testar subsistemas embarcados, com ênfase na aplicação de técnicas de injeção de dependências. Essas técnicas são particularmente úteis em sistemas legados, onde a arquitetura inicial pode não ter sido projetada com foco explícito em testabilidade.

Os exemplos neste documento serão ilustrados em C++.

* Motivação
Ao realizar um teste, o objetivo é validar, com certo grau de confiança, que o sistema atende aos requisitos definidos. A eficácia de um teste pode ser avaliada com base em diversos critérios, notadamente:

- *Fidelidade*: O quão próximo o ambiente de teste reflete as condições do ambiente real de operação.
- *Reprodutibilidade*: A consistência dos resultados em execuções sob as mesmas condições.
- *Isolamento*: A capacidade de testar um subsistema de forma independente do restante do sistema.

Por vezes, esses critérios podem se conflitar. Por exemplo, um teste com alta fidelidade pode incluir variáveis externas que prejudiquem tanto a reprodutibilidade quanto o isolamento. Imagine testar o envio de dados de um cliente IoT para um servidor real (alta fidelidade). Se o servidor estiver indisponível ou sofrer alterações, o resultado do teste pode se tornar incerto (baixa reprodutibilidade) ou exigir muita coordenação (baixo isolamento).

Essas considerações destacam a importância de uma estratégia robusta de testes que vá desde unidades isoladas até a integração completa de todos os subsistemas. Neste artigo, focaremos na aplicação da *injeção de dependências* para viabilizar testes unitários em C++.

* Injeção de dependências
Em nosso contexto, uma "dependência" representa um componente de software necessário para implementar um requisito. Exemplos incluem:
- Uma função que efetua a leitura de um sensor de temperatura.
- Um conjunto de classes que escaneiam bytes vindos da porta serial e os interpretam como logins RFID.
- SDK para envio de telemetria.
- Controlador PID.

Nem sempre temos total controle sobre nossas dependências, seja por elas serem bibliotecas externas, seja por envolverem acesso a hardware diretamente. Nessas situações, testá-las em ambientes reais pode ser inviável ou inconveniente.

Semelhante ao uso de modelos para representar a realidade, nos interessa substituir uma dependência real por uma versão simplificada, permitindo testar o componente de forma isolada. A injeção de dependências se baseia exatamente nessa ideia.

A essência da abordagem é declarar dependências como abstrações (em oposição a ligações fixas diretamente no código), delegando a tarefa de fornecer implementações concretas ao componente que chamará o sistema. Em geral, isso acontece próximo ao ponto de entrada do software, como na função ~main~ ou equivalente.

* O subsistema a ser testado
Para ilustrar, considere uma API para envio de requisições HTTP:

#+BEGIN_SRC cpp
namespace http {
struct Request;

enum class Status {
  Okay,
  Fail
};

Status post(const Request&);
}
#+END_SRC

Essa API é imutável, pois pode fazer parte de um SDK proprietário ou de terceiros e, portanto, não temos controle sobre seu comportamento nem podemos alterá-la.

Agora, considere o seguinte subsistema que utiliza essa API para enviar medições:

#+BEGIN_SRC cpp
struct Measurement;

http::Request to_request(const Measurement&);

void send_measurement(const Measurement& measurement, int max_attempts) {
  const auto request = to_request(measurement);
  
  for (int attempt = 0; attempt < max_attempts; ++attempt) {
    const auto status = http::post(request);
    if (status == http::Status::Okay) {
      return;
    }
  }
}
#+END_SRC

Nosso objetivo é testar a função ~send_measurement~, garantindo que ela tenta enviar uma requisição exatamente =N= vezes em caso de =N= falhas consecutivas nas chamadas HTTP. A API dessa função deve permanecer inalterada para garantir a compatibilidade com o código existente.

A luz da discussão sobre testes unitários, constatamos que testar diretamente a API HTTP enfrentaria problemas como:
- Dependência de um servidor externo, que pode estar indisponível.
- Complexidade para simular falhas no servidor.
- Testes lentos e caros devido à utilização de uma infraestrutura real.

Como solução, propomos substituir a dependência direta da função ~http::post~ por uma versão simulada (*Fake*) durante os testes.

* Técnicas de Injeção de Dependências

** Classes abstratas e resolução dinâmica
Uma abordagem inicial faz uso de classes abstratas para permitir polimorfismo dinâmico:

#+BEGIN_SRC cpp
// Camada de indireção que nos possibilita controlar o que de fato executa. 
class Client {
public:
  virtual ~Client() = default;

  virtual http::Status post(const http::Request&) const = 0;
};

// A implementação real simplemente delega ao http::post.
class HttpClient : public Client {
public:
  http::Status post(const http::Request& req) const override {
    return http::post(req);
  }
};

void send_measurement(const Measurement& measurement, int max_attempts,
                      const Client& client = HttpClient{}) {
  const auto request = to_request(measurement);

  for (int attempt = 0; attempt < max_attempts; ++attempt) {
    const auto status = client.post(request);
    if (status == http::Status::Okay) {
      return;
    }
  }
}

// Implementação para testes, sempre devolve um status pré-definido e incrementa um contador cada vez que executa um envio.
class CountingClient : public Client {
public:
  explicit CountingClient(http::Status fixedStatus) : status{fixedStatus} {}

  http::Status post(const http::Request&) const override {
    ++attempts;
    return status;
  }

  mutable int attempts{0}; // mutable permite modificar o estado dentro de funções const, útil em testes.
  http::Status status;
};

void test() {
  constexpr int expected_attempts = 10;
  CountingClient client_always_fail{http::Status::Fail};
  
  send_measurement(Measurement{}, expected_attempts, client_always_fail);

  assert(client_always_fail.attempts == expected_attempts);
}
#+END_SRC

Note que ~send_measurement~ agora recebe um terceiro parâmetro: ~const Client& client = HttpClient{}~. É ele que nos possibilita substituir a real chamada HTTP por algo que esteja sob nosso controle. Além disso, lhe demos um argumento padrão para preservar a compatibilidade com o código existente. Apesar de haver outras formas com diferentes prós e constras de se atingir o mesmo objetivo (e.g. sobrecarga de funções), o argumento padrão será utilizado enquanto estratégia ao longo desse texto sem perda de generalidade. 

Com respeito ao uso de polimorfismo dinâmico, temos aproximadamente:
- *Vantagens*: Flexibilidade em tempo de execução, fácil substituição de implementações, e baixo impacto no tempo de execução e moderado tamanho do binário.
- *Desvantagens*: Overhead de resolução dinâmica (interfaces virtuais) e maior dependência maior do uso de ponteiros e referências.

*** Caso especial: ~std::function<>~
Para casos em que a API resume-se a única função, uma abordagem alternativa e mais compacta e termos de código escrito consiste em usar a [[https://en.cppreference.com/w/cpp/utility/functional/function.html][~std::function<>~]] para definir o comportamento dinamicamente sem necessidade de hierarquia de classes:

#+BEGIN_SRC cpp
//
using PostFn = std::function<http::Status(const http::Request&)>;

void send_measurement(const Measurement& measurement, int max_attempts,
                      const PostFn& post = http::post) {
  const auto request = to_request(measurement);

  for (int attempt = 0; attempt < max_attempts; ++attempt) {
    const auto status = post(request);
    if (status == http::Status::Okay) {
      return;
    }
  }
}

class CountingClient {
public:
  explicit CountingClient(http::Status fixedStatus) : status{fixedStatus} {}

  http::Status operator()(const http::Request &) {
    ++attempts;
    return status;
  }

  http::Status status;
  int attempts{0};
};

void test() {
  constexpr int expected_attempts = 10;
  CountingClient client_always_fail{http::Status::Fail};

  send_measurement(Measurement{}, expected_attempts,
                   std::ref(client_always_fail));

  assert(client_always_fail.attempts == expected_attempts);
}
#+END_SRC

Considerações sobre ~std::function<>~:
- *Vantagens*: Mais simples que classes abstratas, reduz verbosidade.
- *Desvantagens*: Similares ao uso de classes abstratas.

Vale destacar que em alguns cenários podemos atingir o objetivo com um ponteiro para função, e.g. se o objeto passado não possuí estado.

** Templates e resolução estática
Uma alternativa com *templates* explora polimorfismo em tempo de compilação:

#+BEGIN_SRC cpp
template <typename Client = HttpClient>
void send_measurement(const Measurement &measurement, int max_attempts,
                      const Client &client = HttpClient{}) {
  const auto request = to_request(measurement);

  for (int attempt = 0; attempt < max_attempts; ++attempt) {
    const auto status = client.post(request);
    if (status == http::Status::Okay) {
      return;
    }
  }
}

class CountingClient {
public:
  explicit CountingClient(http::Status fixedStatus) : status{fixedStatus} {}

  http::Status post(const http::Request &) const {
    ++attempts;
    return status;
  }

  http::Status status;
  mutable int attempts{0};
};

void test() {
  constexpr int expected_attempts = 10;

  CountingClient client_always_fail{http::Status::Fail};
  send_measurement(Measurement{}, expected_attempts, client_always_fail);

  assert(client_always_fail.attempts == expected_attempts);
}
#+END_SRC

#+RESULTS:

Considerações sobre templates:
- *Vantagens*: Maior eficiência em tempo de execução com mais possibilidades para "inlining" e checagem de erros em tempo de compilação.
- *Desvantagens*: Código pode se tornar mais verboso com piores mensagem de erro de compilação, aumento no tamanho do binário e maior tempo de compilação.

*** Caso especial: função

#+BEGIN_SRC cpp
template <typename PostFn = decltype(http::post)>
void send_measurement(const Measurement &measurement, int max_attempts,
                      PostFn post = http::post) {
  const auto request = to_request(measurement);

  for (int attempt = 0; attempt < max_attempts; ++attempt) {
    const auto status = post(request);
    if (status == http::Status::Okay) {
      return;
    }
  }
}

class CountingClient {
public:
  explicit CountingClient(http::Status fixedStatus) : status{fixedStatus} {}

  http::Status operator()(const http::Request &) {
    ++attempts;
    return status;
  }

  http::Status status;
  int attempts{0};
};

void test() {
  constexpr int expected_attempts = 10;
  CountingClient client_always_fail{http::Status::Fail};

  send_measurement(Measurement{}, expected_attempts,
                   std::ref(client_always_fail));

  assert(client_always_fail.attempts == expected_attempts);
}
#+END_SRC


* Conclusão
A injeção de dependências é uma técnica valiosa para aprimorar a testabilidade de software embarcado, permitindo isolar e simular componentes de forma eficaz. As abordagens discutidas oferecem diferentes vantagens:

- *Classes abstratas*: Proporcionam flexibilidade em tempo de execução.
- *std::function<>*: Oferecem simplicidade em cenários específicos e menor acoplamento a hierarquias complexas.
- *Templates*: Garantem alto desempenho, mas exigem maior verbosidade e aumentam o tempo de compilação.

É importante destacar que o impacto de cada abordagem no projeto (e.g. desempenho) depende de uma série de fatores que devem ser avaliados e monitorados continuamente para uma caracterização mais precisa. Comparar diretamente diferentes técnicas pode ser impreciso, já que cada solução oferece capacidades distintas e são úteis em diferentes contextos. Portanto, é recomendável avaliar as opções caso a caso, considerando a possibilidade de combiná-las para atender às necessidades específicas do projeto.

Concluindo, agora com respeito à estratégia de testes, a escolha da abordagem mais adequada deve considerar a realidade do sistema e buscar um equilíbrio entre fidelidade, isolamento e reprodutibilidade. Em particular, sistemas embarcados se beneficiam de estratégias que reduzem os impactos do hardware envolvido e aumentam a confiabilidade do software.
