#+begin_export html
---
layout: post
title: Testabilidade e Injeção de Dependências em Software Embarcado
permalink: /:title/
tags: [testes c++]
---
#+end_export

#+BEGIN_QUOTE
Uma breve introdução a técnicas de injeção de dependências em C++ para testes unitários de software embarcado.
#+END_QUOTE

---

* Introdução

A *testabilidade* é um aspecto crucial no desenvolvimento de sistemas embarcados, especialmente devido ao impacto significativo que esses dispositivos têm em contextos críticos, como veículos, equipamentos médicos e sistemas industriais. Testes unitários, nesse cenário, assumem um papel estratégico ao permitir a validação isolada de cada unidade de código. Isso contribui para a detecção precoce de defeitos, reduzindo os riscos associados à integração de componentes e oferecendo feedback contínuo durante o desenvolvimento.

Entretanto, o ambiente embarcado apresenta desafios únicos, como restrições de hardware, recursos computacionais limitados e dificuldades para simular cenários críticos. Esses fatores reforçam ainda mais a necessidade de uma abordagem estruturada para testes.

Neste artigo, exploraremos estratégias práticas para isolar e testar subsistemas embarcados, com ênfase na aplicação de técnicas de injeção de dependências. Tais técnicas são especialmente úteis em sistemas legados, cuja arquitetura inicial pode não ter priorizado a testabilidade..

Os exemplos neste documento serão ilustrados em C++.

* Motivação

Ao realizar um teste, o objetivo é validar, com certo grau de confiança, que o sistema atende aos requisitos definidos. A eficácia de um teste pode ser avaliada com base em diversos critérios, notadamente:

+ *Fidelidade*: O quão próximo o ambiente de teste reflete as condições do ambiente real de operação.
+ *Reprodutibilidade*: A consistência dos resultados em execuções sob as mesmas condições.
+ *Isolamento*: A capacidade de testar um subsistema de forma independente do restante do sistema.

Por vezes, esses critérios podem se conflitar. Por exemplo, um teste com alta fidelidade pode incluir variáveis externas que prejudiquem tanto a reprodutibilidade quanto o isolamento. Imagine testar o envio de dados de um cliente IoT para um servidor real (alta fidelidade). Se o servidor estiver indisponível ou sofrer alterações, o resultado do teste pode se tornar incerto (baixa reprodutibilidade) ou exigir muita coordenação (baixo isolamento).

Essas considerações destacam a importância de uma estratégia robusta de testes, abrangendo desde unidades isoladas até a integração completa de todos os subsistemas.

Neste artigo, focaremos na aplicação da *injeção de dependências* para viabilizar testes unitários em C++.

* Injeção de dependências

Em nosso contexto, uma "dependência" representa um componente de software necessário para implementar um requisito. Exemplos incluem:

+ Uma função que efetua a leitura de um sensor de temperatura.
+ Um conjunto de classes que escaneiam bytes vindos da porta serial e os interpretam como logins RFID.
+ SDK para envio de telemetria.
+ Controlador PID.

Nem sempre temos total controle sobre nossas dependências, seja por elas serem bibliotecas externas, seja por envolverem acesso a hardware diretamente. Nessas situações, testá-las em ambientes reais pode ser inviável ou inconveniente.

Semelhante ao uso de modelos para representar a realidade, nos interessa substituir uma dependência real por uma versão simplificada, nos permitindo testar o componente de forma isolada. Em resumo, gostaríamos de isolar e controlar dependências de um determinado subsistema que causem não-determinismo ou similares efeitos colaterais fora de nosso controle em um contexto em que buscamos testar apenas o dito subsistema.

É isso que injeção de dependências nos possibilita.

A essência da abordagem é fazer com que o subsistema objeto de testes declare suas dependências como abstrações (em oposição a ligações fixas amarradas internamente pelo próprio subsistema), delegando a tarefa de fornecer implementações concretas ao componente externo que usará o subsistema. Tipicamente, isso acontece próximo ao ponto de entrada do software, como na função ~main~ ou equivalente.

Com isso, os testes podem definir seus próprios objetos de teste que satisfação a abstração e que sejam convenientes para verificar determinados comportamentos.

*** Considerações sobre Fakes, Mocks e Stubs

Há diferentes tipos de substitutos para testes e a nomenclatura é [[https://martinfowler.com/articles/mocksArentStubs.html][diversa]] e por vezes confusa, por exemplo:
+ *Fake*: Implementação funcional simplificada, usada para testes.
+ *Stub*: Retorna valores pré-definidos, sem lógica.
+ *Mock*: Permite verificar interações (e.g. número de chamadas, argumentos).

Ao longo desse texto, utilizarei o termo /Fake/ sem muito preciosismo quanto ao seu significado "exato".

* O subsistema a ser testado

Para ilustrar, considere uma API para envio de requisições HTTP:

#+BEGIN_SRC cpp
namespace http {
struct Request;

enum class Status {
  Okay,
  Fail
};

Status post(const Request&);
}
#+END_SRC

Essa API é imutável, pois pode fazer parte de um SDK proprietário ou de terceiros e, portanto, não temos controle sobre seu comportamento nem podemos alterá-la.

Agora, considere o seguinte subsistema que utiliza essa API para enviar medições:

#+BEGIN_SRC cpp
struct Measurement {
  // Fictício.
};

http::Request to_request(const Measurement& m) {
  // Conversão fictícia para exemplo.
  return http::Request{/*...*/};
}

void send_measurement(const Measurement& measurement, int max_attempts) {
  const auto request = to_request(measurement);

  for (int attempt = 0; attempt < max_attempts; ++attempt) {
    const auto status = http::post(request);
    if (status == http::Status::Okay) {
      return;
    }
  }
}
#+END_SRC

Nosso objetivo é testar a função ~send_measurement~, garantindo que ela envie uma requisição exatamente ~N~ vezes em caso de ~N~ falhas consecutivas nas chamadas HTTP. Para simular restrições minimamente realistas de projeto prático, buscaremos minizar a quantidade de código a ser alterada e sendo assim será necessário manter a retrocompatibilidade com o código existente.

À luz da discussão sobre testes unitários, constatamos que usar a API HTTP real nos testes produziria os seguintes incovenientes:

+ Dependência de um servidor externo, que pode estar indisponível.
+ Complexidade para simular falhas no servidor.
+ Testes lentos e caros devido à utilização de uma infraestrutura real.

Como solução, propomos substituir a dependência direta da função ~http::post~ por uma versão simulada (/Fake/) sob medida para testes.

* Técnicas de Injeção de Dependências

** Classes abstratas e resolução dinâmica

Uma abordagem inicial faz uso de classes abstratas para permitir polimorfismo dinâmico:

#+BEGIN_SRC cpp
class Client {
public:
  virtual ~Client() = default;
  virtual http::Status post(const http::Request&) const = 0;
};

class HttpClient : public Client {
public:
  http::Status post(const http::Request& req) const override {
    return http::post(req);
  }
};

void send_measurement(const Measurement& measurement, int max_attempts,
                      const Client& client = HttpClient{}) {
  const auto request = to_request(measurement);

  for (int attempt = 0; attempt < max_attempts; ++attempt) {
    const auto status = client.post(request);
    if (status == http::Status::Okay) {
      return;
    }
  }
}

// Fake para testes: conta tentativas e retorna status fixo.
class CountingClient : public Client {
public:
  explicit CountingClient(http::Status fixedStatus) : status{fixedStatus} {}

  http::Status post(const http::Request&) const override {
    ++attempts;
    return status;
  }

  mutable int attempts{0}; // "mutable" permite modificar o estado dentro de funções-membra "const". Perigoso em código de produção, porém útil em testes.
  http::Status status;
};

void test() {
  constexpr int expected_attempts = 10;
  CountingClient client_always_fail{http::Status::Fail};

  send_measurement(Measurement{}, expected_attempts, client_always_fail);

  assert(client_always_fail.attempts == expected_attempts);
}
#+END_SRC

Note que ~send_measurement~ agora recebe um terceiro parâmetro: ~const Client& client = HttpClient{}~. É ele que nos possibilita substituir a real chamada HTTP por algo que esteja sob nosso controle. Sendo essa a essência da injeção de dependências.

Além disso, lhe demos um argumento padrão (por simplicidade, instanciado a cada chamada) para preservar a compatibilidade com o código existente. Apesar de haver outras formas com diferentes prós e contras de se atingir o mesmo objetivo (e.g. sobrecarga de funções, passagem explícita de argumentos), o argumento padrão será utilizado enquanto estratégia ao longo desse texto por simplicidade sem perda de generalidade.

Já no teste, utilizamos um /Fake/ que simplesmente retorna uma resposta de falha pré-definida e mantém um contador do número de chamadas feitas ao método. Esse contador pode ser inspecionado para confirmar que corresponde ao valor esperado.

Note que /Fakes/ podem ser muito mais elaborados. Por exemplo, poderíamos substituir o contador por um contêiner (e.g. ~std::vector<http::Request>~) que armazena os argumentos fornecido ao ~post~ e assim poderíamos verificar cenários em ~send_measurement~ o chama com diferentes argumentos. Neste caso, o número de chamadas equivaleria ao número de elementos no contêiner.

#+begin_center
O uso de ~mutable~ exige cautela, pois pode introduzir, de forma não intencional, violações de "[[https://isocpp.org/wiki/faq/const-correctness][const correctness]]". Ainda assim, seu emprego pode ser necessário em *testes*.
#+end_center

Considerações:
+ *Vantagens*:
  + Flexibilidade em tempo de execução.
  + Fácil substituição de implementações.
  + Baixo impacto no tempo de execução e moderado tamanho do binário.
+ *Desvantagens*:
  + Overhead de resolução dinâmica (interfaces virtuais).
  + Maior dependência do uso de ponteiros e referências.

** Caso especial: ~std::function<>~

Para casos em que a API resume-se a uma única função, pode-se usar [[https://en.cppreference.com/w/cpp/utility/functional/function.html][~std::function<>~]] para definir o comportamento dinamicamente sem necessidade de hierarquia de classes, o que torna a implementação menos verbosa:

#+BEGIN_SRC cpp
// Camada de indireção para substituição dinâmica.
using PostFn = std::function<http::Status(const http::Request&)>;

void send_measurement(const Measurement& measurement, int max_attempts,
                      const PostFn& post = http::post) {
  const auto request = to_request(measurement);

  for (int attempt = 0; attempt < max_attempts; ++attempt) {
    const auto status = post(request);
    if (status == http::Status::Okay) {
      return;
    }
  }
}

class CountingClient {
public:
  explicit CountingClient(http::Status fixedStatus) : status{fixedStatus} {}

  // Implementamos o operador chamada de função para que "CountingClient" seja compatível com "std::function".
  http::Status operator()(const http::Request &) const {
    ++attempts;
    return status;
  }

  http::Status status;
  mutable int attempts{0};
};

void test() {
  constexpr int expected_attempts = 10;
  CountingClient client_always_fail{http::Status::Fail};

  send_measurement(Measurement{}, expected_attempts,
                   std::cref(client_always_fail));

  assert(client_always_fail.attempts == expected_attempts);
}
#+END_SRC

Note o uso de [[https://en.cppreference.com/w/cpp/utility/functional/ref.html][~std::cref~]] para impedir a cópia de ~client_always_fail~. Isso garante que seja passado por referência, permitindo que qualquer modificação feita em ~client_always_fail~ dentro da função ~send_measurement~ seja refletida após sua execução.

Alternativamente, poderíamos implementar o /Fake/ como uma expressão lambda, sem a necessidade de uma classe, e.g.:

#+begin_src cpp
int attempts = 0;
const auto client_always_fail = [&attempts](const http::Request &)  {
  ++attempts;
  return http::Status::Fail;
};

send_measurement(Measurement{}, expected_attempts, client_always_fail);

assert(attempts == expected_attempts);
#+end_src

Considerações:
+ *Vantagens*:
  + Mais simples que classes abstratas.
  + Reduz verbosidade.
+ *Desvantagens*:
  + Overhead de ~std::function~ pode ser relevante em ambientes embarcados restritos e/ou sem acesso ao "heap".
  + Requer refatoração para acomodar múltiplas funções.

** Templates e resolução estática

Uma alternativa com *templates* explora polimorfismo estático, resolvendo chamadas em tempo de compilação:

#+BEGIN_SRC cpp
class HttpClient {
public:
  http::Status post(const http::Request &req) const { return http::post(req); }
};

// Nossa camada de indireção passa a ser o template.
template <typename Client = HttpClient>
void send_measurement(const Measurement &measurement, int max_attempts,
                      const Client &client = HttpClient{}) {
  const auto request = to_request(measurement);

  for (int attempt = 0; attempt < max_attempts; ++attempt) {
    const auto status = client.post(request);
    if (status == http::Status::Okay) {
      return;
    }
  }
}

class CountingClient {
public:
  explicit CountingClient(http::Status fixedStatus) : status{fixedStatus} {}

  http::Status post(const http::Request &) const {
    ++attempts;
    return status;
  }

  http::Status status;
  mutable int attempts{0};
};

void test() {
  constexpr int expected_attempts = 10;

  CountingClient client_always_fail{http::Status::Fail};
  send_measurement(Measurement{}, expected_attempts, client_always_fail);

  assert(client_always_fail.attempts == expected_attempts);
}
#+END_SRC

Considerações:
+ *Vantagens*:
  + Maior eficiência em tempo de execução.
  + Possibilidades para "inlining" e otimizações correlatas.
+ *Desvantagens*:
  + Aumento no tamanho do binário e maior tempo de compilação.
  + Complica a compilação em unidades de compilação separadas, pois para compilar cada chamado ao template o compilador requer acesso a sua definição.
  + Qualidade das mensagens de erro de compilação.

** Caso especial: função como template

#+BEGIN_SRC cpp
// Nossa camada de indireção passa a ser algo "tipo" uma função.
template <typename PostFn = decltype(&http::post)>
void send_measurement(const Measurement &measurement, int max_attempts,
                      const PostFn& post = http::post) {
  const auto request = to_request(measurement);

  for (int attempt = 0; attempt < max_attempts; ++attempt) {
    const auto status = post(request);
    if (status == http::Status::Okay) {
      return;
    }
  }
}

class CountingClient {
public:
  explicit CountingClient(http::Status fixedStatus) : status{fixedStatus} {}

  // Implementamos o operador chamada de função para que "CountingClient" seja compatível com o template.
  http::Status operator()(const http::Request &) const {
    ++attempts;
    return status;
  }

  http::Status status;
  mutable int attempts{0};
};

void test() {
  constexpr int expected_attempts = 10;
  CountingClient client_always_fail{http::Status::Fail};

  send_measurement(Measurement{}, expected_attempts,
                   std::cref(client_always_fail));

  assert(client_always_fail.attempts == expected_attempts);
}
#+END_SRC

Similar ao ~std::function>~, podemos também alcançar o mesmo objetivo com uma expressão lambda em lugar da classe ~CountingClient~.

Considerações:
+ *Vantagens*:
  + Mais simples que classes, reduz verbosidade.
+ *Desvantagens*:
  + Similares ao uso de templates.
  + Requer refatoração para múltiplas funções.

*** Conceitos (C++ >=20)

Citamos a diminuição da qualidade dos erros de compilação como sendo uma desvantagem dos templates.

Isso é largamente mitigado com o uso de "[[https://en.cppreference.com/w/cpp/language/constraints.html][concepts]]" que estão disponíveis a partir da versão 20 do C++. Assim, podemos, por exemplo, refinar nosso template a tipos que suportem o operador chamada de função, que aceitem um ~http::Request~ como parâmetro e que retornem um ~http::Status~, e.g.:

#+begin_src cpp
template <typename F>
concept PostFunction =
    std::invocable<F, const http::Request&> &&
    std::same_as<std::invoke_result_t<F, const http::Request&>, http::Status>;

template <PostFunction PostFn = decltype(&http::post)>
void send_measurement(const Measurement &measurement, int max_attempts,
                      const PostFn& post = http::post) {
#+end_src


* Conclusão

A injeção de dependências é uma técnica valiosa para aprimorar a testabilidade de software embarcado, permitindo isolar e simular componentes de forma eficaz. As abordagens discutidas oferecem diferentes vantagens:

- *Classes abstratas*: Proporcionam flexibilidade em tempo de execução.
- *Templates*: Garantem alto desempenho, mas exigem maior verbosidade e aumentam o tempo de compilação.

É importante destacar que o impacto de cada abordagem no projeto (e.g. viabilidade, desempenho) depende de uma série de fatores que devem ser avaliados e monitorados continuamente para uma caracterização mais precisa. Comparar diretamente diferentes técnicas pode ser impreciso, já que cada solução oferece capacidades distintas e são úteis em diferentes contextos. Portanto, é recomendável avaliar as opções caso a caso, considerando inclusive a possibilidade de combiná-las para atender às necessidades específicas do projeto.

Concluindo, agora com respeito à estratégia de testes, a escolha da abordagem mais adequada deve considerar a realidade do sistema e buscar o equilíbrio entre fidelidade, isolamento e reprodutibilidade. Em particular, sistemas embarcados se beneficiam de estratégias que reduzem os impactos do hardware envolvido e aumentam a confiabilidade do software, o que pode abranger testes automatizados e manuais em diferentes escalas.
