name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install dependencies
        run: sudo apt-get update && apt-get install -y pandoc && bundle install && bundle exec appraisal install
      - name: Convert org to md
        run: |
          find ./ -iname "*.org" -type f -exec sh -c 'pandoc -f org -t gfm "${0}" -o "${0%.org}.md"' {} \;
          find . -name "*.org" -type f -delete
      - name: Setup Pages
        id: configure-pages
        uses: actions/configure-pages@v5
      - name: Setup CI config
        run: |
          echo "---" > _config_ci.yml
          echo "baseurl: ${{ steps.configure-pages.outputs.base_path }}" >> _config_ci.yml
      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec appraisal jekyll build --future --config _config_ci.yml,_config.yml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
